# Generated by Django 2.2.5 on 2019-12-15 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answered_Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='captcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'web problem'), (2, 'misc problem'), (3, 'pwn problem'), (4, 'crypto problem'), (5, 'reverse problem')])),
                ('answer', models.CharField(max_length=255)),
                ('uploader', models.CharField(default='original', max_length=20)),
                ('scores', models.IntegerField(default=0)),
                ('address', models.CharField(default='', max_length=255)),
                ('answered_user_number', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='problem_solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('introduction', models.CharField(max_length=255)),
                ('check', models.BooleanField(default=False)),
                ('good', models.IntegerField(default=0)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CTFweb.Answer_Ship')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=10, unique=True)),
                ('leader', models.CharField(max_length=10)),
                ('member_num', models.IntegerField(default=1)),
                ('answers', models.IntegerField(default=0)),
                ('scores', models.IntegerField(default=0)),
                ('web', models.IntegerField(default=0)),
                ('misc', models.IntegerField(default=0)),
                ('pwn', models.IntegerField(default=0)),
                ('crypto', models.IntegerField(default=0)),
                ('reverse', models.IntegerField(default=0)),
                ('motto', models.CharField(default='To be or not to be is a problem', max_length=255)),
            ],
            options={
                'verbose_name': '队伍',
                'verbose_name_plural': '队伍',
                'ordering': ['-scores'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('stu_id', models.CharField(max_length=10, unique=True)),
                ('scores', models.IntegerField(default=0)),
                ('answers', models.IntegerField(default=0)),
                ('web', models.IntegerField(default=0)),
                ('misc', models.IntegerField(default=0)),
                ('pwn', models.IntegerField(default=0)),
                ('crypto', models.IntegerField(default=0)),
                ('reverse', models.IntegerField(default=0)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('motto', models.CharField(default="I'm lazy so here's no motto.", max_length=255)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CTFweb.Team')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-scores'],
            },
        ),
        migrations.CreateModel(
            name='user_wp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ag_time', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CTFweb.User')),
                ('wp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CTFweb.problem_solution')),
            ],
        ),
        migrations.CreateModel(
            name='user_application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_time', models.TimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CTFweb.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CTFweb.User')),
            ],
            options={
                'ordering': ['apply_time'],
            },
        ),
        migrations.CreateModel(
            name='Problem_Team_Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_member_num', models.IntegerField(default=1)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CTFweb.Problem')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CTFweb.Team')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='answered_team',
            field=models.ManyToManyField(through='CTFweb.Problem_Team_Ship', to='CTFweb.Team'),
        ),
        migrations.AddField(
            model_name='problem',
            name='answered_user',
            field=models.ManyToManyField(through='CTFweb.Answer_Ship', to='CTFweb.User'),
        ),
        migrations.AddField(
            model_name='answer_ship',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CTFweb.Problem'),
        ),
        migrations.AddField(
            model_name='answer_ship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CTFweb.User'),
        ),
    ]
